# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 target 'RNPodcastApp' do
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

end

