
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_TOP_COMMENT = "GET_TOP_COMMENT"
export const TOGGLE_REPLY="TOGGLE_REPLY"
export const SET_CURRENT_TIME = "SET_CURRENT_TIME"
export const TOGGLE_MINIMIZED="TOGGLE_MINIMIZED"
export const TOGGLE_HAS_REPLIES="TOGGLE_HAS_REPLIES"



//* ------- PLAYER TYPES --------*//
export const SET_CURRENT_PLAYBACK_MODE="SET_CURRENT_PLAYBACK_MODE"

//* ------- REQUEST TYPES --------*//
export const REQUEST_COMMENTS_BY_PODCAST = "REQUEST_COMMENTS_BY_PODCAST"
export const REQUEST_ADD_COMMENT = "REQUEST_ADD_COMMENT"

//* ------- RECEIVED TYPES --------*//
export const RECEIVED_COMMENTS_BY_PODCAST = "RECEIVED_COMMENTS_BY_PODCAST"
export const RECEIVED_COMMENTS_BY_PODCAST_ERROR = "RECEIVED_COMMENTS_BY_PODCAST_ERROR"
export const RECEIVED_NEW_COMMENT = "RECEIVED_NEW_COMMENT"
export const RECEIVED_NEW_COMMENT_ERROR ="RECEIVED_NEW_COMMENT_ERROR"